name: Scheduler
on:
  schedule:
    - cron: "0 20 * * *" # 20:00 UTC
  workflow_dispatch:
jobs:
  update-sponsors:
    name: Update sponsors
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
      - name: Setup Node.js@lts environment
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build:sponsorkit
        env:
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}
      # - run: pnpm run build
      - run: pnpm run start:tsx
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: update sponsors.svg [ci skip]"
          add: "sponsorkit/sponsors.*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
